<section class="panier">
	<div class="clearfix">
		<form class="form" method="POST">
			<input type="hidden" name="action" value="v_order">
			<div>
				<p>Prix : <?=htmlentities($cart->getPrice())?>€</p>
				<p>Date : <?=htmlentities($cart->getDate())?></p>
			</div>
			<button type="submit" class="btn btn-default">Valider le panier</button>
		</form>
		<?php require('apps/cart_elem.php'); ?>
	</div>
</section>