<div class="alert">
	<div class="contact">
		<h2>Une question ? un problème ?</h2>
		<div class="container">
		<div class="col-md-10">
		    <div class="form-area">  
		        <form role="form">
			        <br style="clear:both">
		            <h3 style="margin-bottom: 25px; text-align: center;">Formulaire de contact</h3>
					<div class="form-group">
						<input type="text" class="form-control" id="name" name="name" placeholder="Nom, prénom" required>
					</div>
					<div class="form-group">
						<input type="text" class="form-control" id="email" name="email" placeholder="Email" required>
					</div>
					<div class="form-group">
						<input type="text" class="form-control" id="subject" name="subject" placeholder="Sujet" required>
					</div>
		            <div class="form-group">
		            <textarea class="form-control" type="textarea" id="message" placeholder="Message" maxlength="140" rows="7"></textarea>
		            </div>          
			        <button type="button" id="submit" name="submit" class="btn btn-primary pull-right">Envoyer</button>
		        </form>
		    </div>
		</div>
		</div>
		<div class="coordonnees">
			<strong><h4>Adresse:</h4></strong>
			67 rue de Strasbourg <br>
			67000 STRASBOURG 
			
			<strong><h4>Téléphone:</h4></strong>
			03 88 00 00 00

			<strong><h4>Email:</h4></strong>
			blabla@bla.bla

		</div>
	</div>
</div>