<div class="alert">
<h1>Créer un nouveau produit</h1>
<form method="POST">
	<input type="hidden" name="action" value="create_product">
	<div class="form-group">
		<label for="category">Catégorie</label>
		<select id="category" name="id_category">
			<?php for ($nbr = 0; $nbr < count($list); $nbr++) : ?>
			<option value="<?=$list[$nbr]->getId()?>"><?=$list[$nbr]->getName()?></option>
			<?php endfor; ?>
		</select>
		<!-- 	<?php foreach ($list AS $category) : ?>
			<option><?=$category->getName()?></option>
			<?php endforeach; ?>
		</select> -->
	</div>
	<div class="form-group">
		<label for="name">Nom du produit</label>
		<input type="text" class="form-control" id="name" name="name" placeholder="Name">
	</div>
	<div class="form-group">
		<label for="picture">Image du produit</label>
		<input type="url" name="picture" id="picture" placeholder="Votre url ici">
	</div>
	<div class="form-group">
		<label for="description">Description</label>
		<textarea class="form-control" id="description" name="description" placeholder="Description"></textarea>
	</div>
	<div class="form-group">
		<label for="price">Prix</label>
		<input type="number" name="price" id="price" placeholder="Le prix du produit ici">
	</div>
	<div class="form-group">
		<label for="quantity">Quantité</label>
		<input type="number" name="quantity" id="quantity" placeholder="La quantité du produit">
	</div>
	<button type="submit" class="btn btn-default">Envoyer</button>
</form>

