<div class="alert">
<h1>Créer une nouvelle catégorie</h1>
<form method="POST">
	<input type="hidden" name="action" value="create_category">
	<div class="form-group">
		<label for="name">Nom de la catégorie</label>
		<input type="text" class="form-control" id="name" name="name" placeholder="Name">
	</div>
	<div class="form-group">
		<label for="description">Description</label>
		<textarea class="form-control" id="description" name="description" placeholder="Description"></textarea>
	</div>
	<button type="submit" class="btn btn-default">Envoyer</button>
</form>
</div>

