<h1>Se connecter</h1>
<form method="POST">
	<?=$ref?>
	<input type="hidden" name="action" value="login">
	<div class="form-group">
		<label for="email">Email</label>
		<input type="text" class="form-control" id="email" name="email" placeholder="Email">
	</div>
	<div class="form-group">
		<label for="password">Mot de passe</label>
		<input type="password" class="form-control" id="password" name="password" placeholder="Mot de passe">
	</div>
	<button type="submit" class="btn btn-default">Envoyer</button>
</form>